# Generated by Django 2.1.5 on 2019-06-12 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_auto_20190610_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recommended',
            field=models.ManyToManyField(to='movies.Movie'),
        ),
    ]
