# Generated by Django 2.1.5 on 2019-06-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_user_recommended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='recommended',
        ),
        migrations.AddField(
            model_name='club',
            name='recommended',
            field=models.ManyToManyField(to='movies.Movie'),
        ),
    ]
